# Generated by Django 5.0.6 on 2024-05-22 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_review_comment_alter_review_star_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star_given',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
