# Generated by Django 5.0.4 on 2024-05-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
